plugins:
  postcss-smart-import: {}
  precss:
    properties:
      disable: true # use CSS Variables
  autoprefixer:
    browsers:
      - last 2 versions
      - IE >= 11
      - iOS >= 9
  postcss-object-fit-images: {}
