version: '3'
services:

  db:
    restart: always
    image: postgres:alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:alpine
    volumes:
      - ./redis:/data

  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: gargron/mastodon-base

  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    image: gargron/mastodon-development
    restart: always
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/mastodon

  webpack:
    build:
      context: .
      dockerfile: Dockerfile.development
    image: gargron/mastodon-development
    restart: always
    command: ./bin/webpack-dev-server --host 0.0.0.0
    ports:
      - "8080:8080"
    volumes:
      - .:/mastodon

  streaming:
    build:
      context: .
      dockerfile: Dockerfile.development
    image: gargron/mastodon-development
    restart: always
    command: npm run start
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/mastodon

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.development
    image: gargron/mastodon-development
    restart: always
    command: bundle exec sidekiq -q default -q mailers -q pull -q push -q remove
    depends_on:
      - db
      - redis
    volumes:
      - .:/mastodon
