# config/app.yml for rails-settings-cached
#
# This file contains default values, and does not need to be edited
# when configuring an instance.  These settings may be changed by an
# Administrator using the Web UI.
#
# For more information, see docs/Running-Mastodon/Administration-guide.md
#
defaults: &defaults
  site_title: Pawoo Music
  site_description: ''
  site_extended_description: ''
  site_terms: ''
  site_contact_username: ''
  site_contact_email: ''
  open_registrations: true
  closed_registrations_message: ''
  open_deletion: true
  timeline_preview: true
  default_sensitive: false
  unfollow_modal: false
  boost_modal: false
  delete_modal: true
  auto_play_gif: false
  system_font_ui: false
  noindex: false
  notification_emails:
    follow: false
    reblog: false
    favourite: false
    mention: false
    follow_request: true
    digest: true
    video_preparation_error: true
    video_preparation_success: true
  notification_firebase_cloud_messagings:
    follow: true
    reblog: true
    favourite: true
    mention: true
    follow_request: false
  interactions:
    must_be_follower: false
    must_be_following: false
  playlist:
    max_queue_size: 10
    max_add_count: 10
    max_skip_count: 2
    skip_limit_time: 90
    replay_history_num: 30
  reserved_usernames:
    - admin
    - support
    - help
    - root
    - webmaster
    - administrator
  bootstrap_timeline_accounts: ''

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
