---
# GMT
:concurrency: 20
:queues:
  - default
  - push
  - pull
  - mailers
  - remove
  - elasticsearch
  - playlist
:schedule:
  subscriptions_scheduler:
    cron: '0 19,0 * * *'
    class: Scheduler::SubscriptionsScheduler
  media_cleanup_scheduler:
    cron: '5 19 * * *'
    class: Scheduler::MediaCleanupScheduler
  feed_cleanup_scheduler:
    cron: '0 15 * * *'
    class: Scheduler::FeedCleanupScheduler
  doorkeeper_cleanup_scheduler:
    cron: '1 1 * * 0'
    class: Scheduler::DoorkeeperCleanupScheduler
  user_cleanup_scheduler:
    cron: '4 5 * * *'
    class: Scheduler::UserCleanupScheduler
  subscriptions_cleanup_scheduler:
    cron: '2 2 * * 0'
    class: Scheduler::SubscriptionsCleanupScheduler
  trend_tag_scheduler:
    cron: '*/30 * * * *'
    class: Scheduler::TrendTagScheduler
